name: Hello World

on:
  push: 
   branches:
    - 'main'
  pull_request:
    branches:
     - 'main'

jobs:
  unittest:
   runs-on: ubuntu-latest

   steps:
    - name: Hello Step
      run: echo "Hello World"
